### ISSUE TITLE
To do tasks

### ISSUE THREAD

**Issue by lezhang7** [lezhang7/Retrieval_MuGI#2]
1. 增加新的rank_model，只需修改https://github.com/lezhang7/Retrieval_MuGI/blob/main/model/reranker.py#L46 中的 `embed`函数，就可以支持新的模型，请添加 naive_rerank，是指直接在bm 25 top100的基础上rerank的结果和在bm25+mugi top 100上rerank的结果
    - [x] https://huggingface.co/intfloat/e5-mistral-7b-instruct 
    - [x] https://huggingface.co/llmrails/ember-v1  
    - [x]  https://huggingface.co/BAAI/bge-large-en-v1.5 
    - [x] 以上基础上，试试mugi pipeline的结果，也就是在rerank的时候还是用生成的文档在bm25+mugi上面排
2. 增加新的开源LLMs生成的psudo documents的ablation,参考https://github.com/lezhang7/Retrieval_MuGI/blob/main/mugi.py#L55，在https://github.com/lezhang7/Retrieval_MuGI/blob/main/model/llm.py 添加新的支持，要包含一个get_answer函数，输入一个prompt,返回答案（去掉乱七八糟的格式之后的纯文本答案），增加新的模型，尽量使用hugginface库中的模型，可使用量化版本以减少内存消耗，在各种模型size版本上实验，最后会除了一个表格，还要画一个lmsys score vs ndcg 的图
    - [x] qwen1.5
    - [x] [Mixtral-8x7b-Instruct-v0.1](https://mistral.ai/news/mixtral-of-experts/)
    - [x] [Yi-34B-Chat](https://huggingface.co/01-ai/Yi-34B-Chat)

**Comment by bareawayme** [comment]
请问可以分享一下下载的topics的文本文件吗？目前那个链接好像关闭了无法下载
